---
# tasks file for nginx
- name: Update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install NGiNX
  apt:
    name: ['nginx']
    state: latest

- name: Copy index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: 0644
  notify: restart nginx
